[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "tab_ml_utils"
version = "0.1.0"
description = "Utilities for tabular machine learning"
requires-python = ">=3.10"

dependencies = [
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "scikit-learn",
    "folktables",
]

[tool.setuptools.packages.find]
where = ["src"]